# Generated by Django 5.1.7 on 2025-03-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("surveycreator", "SurveyCreator"),
                            ("surveyresponder", "SurveyResponder"),
                        ],
                        default="surveyresponder",
                        max_length=15,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("deadline", models.DateTimeField()),
                ("sending_date", models.DateTimeField()),
                ("collected_answer_count", models.IntegerField(default=0)),
                ("is_viewable", models.BooleanField(default=False)),
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_groups",
                    models.ManyToManyField(
                        related_name="published_surveys",
                        to="medarbetarapp.employeegroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                (
                    "question_format",
                    models.CharField(
                        choices=[
                            ("multiplechoice", "MultipleChoice"),
                            ("yesno", "YesNo"),
                            ("text", "Text"),
                            ("slider", "Slider"),
                        ],
                        default="text",
                        max_length=15,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("onetime", "Onetime"),
                            ("reoccurring", "Reoccurring"),
                            ("builtin", "Builtin"),
                            ("enps", "ENPS"),
                        ],
                        default="onetime",
                        max_length=15,
                    ),
                ),
                (
                    "connected_surveys",
                    models.ManyToManyField(
                        related_name="questions", to="medarbetarapp.survey"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("is_answered", models.BooleanField(default=False)),
                (
                    "published_survey",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_results",
                        to="medarbetarapp.survey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_answered", models.BooleanField(default=False)),
                ("comment", models.CharField(max_length=255)),
                ("free_text_answer", models.CharField(max_length=255)),
                ("multiple_choice_answer", models.JSONField(default=list)),
                ("yes_no_answer", models.BooleanField(default=False)),
                ("slider_answer", models.FloatField()),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medarbetarapp.question",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="medarbetarapp.surveyresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("last_edited", models.DateTimeField()),
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_groups",
                    models.ManyToManyField(
                        related_name="survey_templates",
                        to="medarbetarapp.employeegroup",
                    ),
                ),
            ],
        ),
    ]
