# Generated by Django 5.1.7 on 2025-04-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0002_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='free_text_answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='multiple_choice_answer',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='slider_answer',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='yes_no_answer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
