# Generated by Django 5.1.7 on 2025-03-30 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0003_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='userRole',
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='medarbetarapp.organization'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='authorizationLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employeeGroups',
            field=models.ManyToManyField(related_name='employees', to='medarbetarapp.employeegroup'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='managedGroups',
            field=models.ManyToManyField(related_name='managers', to='medarbetarapp.employeegroup'),
        ),
        migrations.AlterField(
            model_name='employeegroup',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeGroups', to='medarbetarapp.organization'),
        ),
    ]
