# Generated by Django 5.1.7 on 2025-03-30 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0005_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastEdited', models.DateTimeField()),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employeeGroups', models.ManyToManyField(related_name='surveyTemplates', to='medarbetarapp.employeegroup')),
            ],
        ),
    ]
