# Generated by Django 5.1.7 on 2025-03-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0006_surveytemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('is_answered', models.BooleanField(default=False)),
                ('publishedSurvey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyResults', to='medarbetarapp.survey')),
            ],
        ),
    ]
