# Generated by Django 5.1.7 on 2025-03-30 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0007_surveyresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='authorizationLevel',
            new_name='authorization_level',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='employeeGroups',
            new_name='employee_groups',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='managedGroups',
            new_name='managed_groups',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='userRole',
            new_name='user_role',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='collectedAnswerCount',
            new_name='collected_answer_count',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='isViewable',
            new_name='is_viewable',
        ),
        migrations.RenameField(
            model_name='surveytemplate',
            old_name='lastEdited',
            new_name='last_edited',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='employeeGroups',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='publishedSurvey',
        ),
        migrations.RemoveField(
            model_name='surveytemplate',
            name='employeeGroups',
        ),
        migrations.AddField(
            model_name='survey',
            name='employee_groups',
            field=models.ManyToManyField(related_name='published_surveys', to='medarbetarapp.employeegroup'),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='published_survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_results', to='medarbetarapp.survey'),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='employee_groups',
            field=models.ManyToManyField(related_name='survey_templates', to='medarbetarapp.employeegroup'),
        ),
        migrations.AlterField(
            model_name='employeegroup',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_groups', to='medarbetarapp.organization'),
        ),
    ]
