# Generated by Django 5.1.7 on 2025-03-31 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0008_rename_authorizationlevel_customuser_authorization_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_answered', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=255)),
                ('free_text_answer', models.CharField(max_length=255)),
                ('multiple_choice_answer', models.JSONField(default=list)),
                ('yes_no_answer', models.BooleanField(default=False)),
                ('slider_answer', models.FloatField()),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='medarbetarapp.surveyresult')),
            ],
        ),
    ]
