# Generated by Django 5.1.7 on 2025-04-01 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0010_rename_managed_groups_customuser_survey_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_format', models.CharField(choices=[('multiplechoice', 'Multiple choice'), ('yesno', 'Yes No'), ('text', 'Text'), ('slider', 'Slider')], default='multiplechoice', max_length=15)),
                ('options', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SliderQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_format', models.CharField(choices=[('multiplechoice', 'Multiple choice'), ('yesno', 'Yes No'), ('text', 'Text'), ('slider', 'Slider')], default='slider', max_length=15)),
                ('max_interval', models.IntegerField(default=10)),
                ('min_interval', models.IntegerField(default=0)),
                ('max_text', models.CharField(max_length=255)),
                ('min_text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_format', models.CharField(choices=[('multiplechoice', 'Multiple choice'), ('yesno', 'Yes No'), ('text', 'Text'), ('slider', 'Slider')], default='text', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YesNoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_format', models.CharField(choices=[('multiplechoice', 'Multiple choice'), ('yesno', 'Yes No'), ('text', 'Text'), ('slider', 'Slider')], default='yesno', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='question_format',
            field=models.CharField(choices=[('multiplechoice', 'Multiple choice'), ('yesno', 'Yes No'), ('text', 'Text'), ('slider', 'Slider')], default='text', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('onetime', 'Onetime'), ('reoccurring', 'Reoccurring'), ('builtin', 'Built in'), ('enps', 'ENPS')], default='onetime', max_length=15),
        ),
        migrations.AddField(
            model_name='question',
            name='multiple_choice_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medarbetarapp.multiplechoicequestion'),
        ),
        migrations.AddField(
            model_name='question',
            name='slider_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medarbetarapp.sliderquestion'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medarbetarapp.textquestion'),
        ),
        migrations.AddField(
            model_name='question',
            name='yes_no_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medarbetarapp.yesnoquestion'),
        ),
    ]
