# Generated by Django 5.1.7 on 2025-04-01 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0011_multiplechoicequestion_sliderquestion_textquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
