# Generated by Django 5.1.7 on 2025-04-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0012_alter_survey_creator_alter_surveytemplate_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='answered_users',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='un_answered_users',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='user_id',
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='medarbetarapp.question'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='employee_groups',
            field=models.ManyToManyField(related_name='+', to='medarbetarapp.employeegroup'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='employee_groups',
            field=models.ManyToManyField(related_name='+', to='medarbetarapp.employeegroup'),
        ),
    ]
