# Generated by Django 5.1.7 on 2025-04-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0013_emaillist_remove_surveyresult_answered_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('surveycreator', 'SurveyCreator'), ('surveyresponder', 'SurveyResponder')], default='admin', max_length=15),
        ),
    ]
