# Generated by Django 5.1.7 on 2025-04-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0014_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_emails', to='medarbetarapp.organization'),
        ),
    ]
