# Generated by Django 5.1.7 on 2025-04-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0014_alter_customuser_user_role'),
        ('medarbetarapp', '0015_alter_emaillist_org'),
        ('medarbetarapp', '0015_emaillist_org'),
    ]

    operations = [
    ]
