# Generated by Django 5.1.7 on 2025-04-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0016_merge_20250404_1211'),
        ('medarbetarapp', '0016_merge_20250407_1439'),
    ]

    operations = [
    ]
