# Generated by Django 5.1.7 on 2025-04-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0016_merge_20250404_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('surveycreator', 'SurveyCreator'), ('surveyresponder', 'SurveyResponder')], default='surveyresponder', max_length=15),
        ),
    ]
