# Generated by Django 5.1.7 on 2025-04-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0017_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='slider_answer',
            field=models.FloatField(null=True),
        ),
    ]
