# Generated by Django 5.1.7 on 2025-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0017_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='employee_groups',
            field=models.ManyToManyField(related_name='group', to='medarbetarapp.employeegroup'),
        ),
    ]
