# Generated by Django 5.1.7 on 2025-04-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0017_alter_customuser_user_role'),
        ('medarbetarapp', '0017_merge_20250409_0813'),
    ]

    operations = [
    ]
