# Generated by Django 5.1.7 on 2025-04-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0018_alter_answer_slider_answer'),
        ('medarbetarapp', '0018_emaillist_employee_groups'),
    ]

    operations = [
    ]
