# Generated by Django 5.1.7 on 2025-04-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0018_merge_20250410_1244'),
        ('medarbetarapp', '0019_merge_20250415_0622'),
    ]

    operations = [
    ]
