# Generated by Django 5.1.7 on 2025-04-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0021_survey_is_anonymous_alter_survey_is_viewable'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='published_count',
            field=models.IntegerField(default=0),
        ),
    ]
