# Generated by Django 5.1.7 on 2025-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0023_rename_surveyresult_surveyuserresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='yes_no_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
