# Generated by Django 5.1.7 on 2025-04-24 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0024_alter_answer_yes_no_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medarbetarapp.question')),
                ('survey_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medarbetarapp.surveytemplate')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('survey_temp', 'question')},
            },
        ),
    ]
