# Generated by Django 5.1.7 on 2025-04-24 07:05

from django.db import migrations

def copy_existing_links(apps, schema_editor):
    QuestionOrder = apps.get_model("medarbetarapp", "QuestionOrder")
    Question = apps.get_model("medarbetarapp", "Question")
    for q in Question.objects.all():
        for survey in q.survey_template.all():
            QuestionOrder.objects.create(survey_temp=survey, question=q, order=0)

class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0025_questionorder'),
    ]

    operations = [
        migrations.RunPython(copy_existing_links),
    ]
