# Generated by Django 5.1.7 on 2025-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0027_remove_survey_template_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='survey_template',
            field=models.ManyToManyField(related_name='questions', through='medarbetarapp.QuestionOrder', to='medarbetarapp.surveytemplate'),
        ),
    ]
