# Generated by Django 5.1.7 on 2025-04-24 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0028_question_survey_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_notification',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
