# Generated by Django 5.1.7 on 2025-04-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0028_question_survey_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
