# Generated by Django 5.1.7 on 2025-04-24 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0029_customuser_last_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_notification',
        ),
        migrations.AddField(
            model_name='survey',
            name='last_notification',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
