# Generated by Django 5.1.7 on 2025-04-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0029_question_question_title'),
        ('medarbetarapp', '0030_remove_customuser_last_notification_and_more'),
    ]

    operations = [
    ]
